from setuptools import setup, find_packages

setup(
    name="multi-agent-ai-research-assistant",
    version="0.1.0",
    author="AI Coding Agent",
    description="A multi-agent system for autonomous ML research workflows",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "scikit-learn>=1.3.0",
        "xgboost>=2.0.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "langchain>=0.1.0",
        "openai>=1.0.0",
        "anthropic>=0.18.0",
        "ray>=2.9.0",
        "celery>=5.3.0",
        "mlflow>=2.10.0",
        "wandb>=0.16.0",
        "psycopg2-binary>=2.9.0",
        "pymongo>=4.6.0",
        "boto3>=1.34.0",
        "fastapi>=0.109.0",
        "uvicorn>=0.27.0",
        "pydantic>=2.6.0",
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0",
        "structlog>=24.1.0",
        "tenacity>=8.2.0",
        "plotly>=5.18.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.0.0",
            "pytest-asyncio>=0.23.0",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
        ],
    },
    python_requires=">=3.10",
    entry_points={
        "console_scripts": [
            "research-assistant=scripts.run_experiment:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
